/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        ink: "var(--color-ink)",
        body: "var(--color-body)",
        mute: "var(--color-mute)",
        hairline: "var(--color-hairline)",
        "hairline-strong": "var(--color-hairline-strong)",
        canvas: "var(--color-canvas)",
        "canvas-soft": "var(--color-canvas-soft)",
        "canvas-soft-2": "var(--color-canvas-soft-2)",
        link: "var(--color-link)",
        "link-deep": "var(--color-link-deep)",
        "link-bg-soft": "var(--color-link-bg-soft)",
        success: "var(--color-success)",
        error: "var(--color-error)",
        "error-soft": "var(--color-error-soft)",
        "error-deep": "var(--color-error-deep)",
        warning: "var(--color-warning)",
        "warning-soft": "var(--color-warning-soft)",
        "warning-deep": "var(--color-warning-deep)",
        violet: "var(--color-violet)",
        "violet-soft": "var(--color-violet-soft)",
        cyan: "var(--color-cyan)",
        "cyan-soft": "var(--color-cyan-soft)",
        "highlight-pink": "var(--color-highlight-pink)",
        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "selection-bg": "var(--color-selection-bg)",
        "selection-fg": "var(--color-selection-fg)",
        coral: "var(--color-coral)",
        "coral-soft": "var(--color-coral-soft)",
        "coral-deep": "var(--color-coral-deep)",
        teal: "var(--color-teal)",
        "teal-soft": "var(--color-teal-soft)",
        "teal-deep": "var(--color-teal-deep)",
        indigo: "var(--color-indigo)",
        "indigo-soft": "var(--color-indigo-soft)",
        "indigo-deep": "var(--color-indigo-deep)",
        amber: "var(--color-amber)",
        "amber-soft": "var(--color-amber-soft)",
        "amber-deep": "var(--color-amber-deep)",
      },
      fontFamily: {
        sans: ["Geist", "Inter", "system-ui", "-apple-system", "sans-serif"],
        mono: [
          "Geist Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "monospace",
        ],
      },
      fontSize: {
        "display-xl": [
          "48px",
          { lineHeight: "48px", letterSpacing: "-2.4px", fontWeight: "600" },
        ],
        "display-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-1.28px", fontWeight: "600" },
        ],
        "display-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.96px", fontWeight: "600" },
        ],
        "display-sm": [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.6px", fontWeight: "600" },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "28px", letterSpacing: "0px", fontWeight: "400" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": [
          "14px",
          { lineHeight: "20px", letterSpacing: "-0.28px", fontWeight: "400" },
        ],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        code: ["13px", { lineHeight: "20px", fontWeight: "400" }],
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "pill-sm": "64px",
        pill: "100px",
        full: "9999px",
      },
      spacing: {
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "40px",
        "3xl": "48px",
        "4xl": "64px",
        "5xl": "96px",
      },
      boxShadow: {
        "level-1": "0 0 0 1px rgba(0,0,0,0.08) inset",
        "level-2":
          "0px 1px 1px rgba(0,0,0,0.02), 0px 2px 2px rgba(0,0,0,0.04), 0 0 0 1px rgba(0,0,0,0.08) inset",
        "level-3":
          "0px 2px 2px rgba(0,0,0,0.04), 0px 8px 8px -8px rgba(0,0,0,0.04), 0 0 0 1px rgba(0,0,0,0.08) inset",
        "level-4":
          "0px 2px 2px rgba(0,0,0,0.04), 0px 8px 16px -4px rgba(0,0,0,0.04), 0 0 0 1px rgba(0,0,0,0.08) inset",
        "level-5":
          "0px 1px 1px rgba(0,0,0,0.02), 0px 8px 16px -4px rgba(0,0,0,0.04), 0px 24px 32px -8px rgba(0,0,0,0.06), 0 0 0 1px rgba(0,0,0,0.08) inset",
      },
    },
  },
  plugins: [],
};
